app = 'jomis7keys'
primary_region = 'fra'

[build]

[env]
NODE_ENV = 'production'
PORT = '3000'

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
min_machines_running = 1

[[http_service.checks]]
interval = '30s'
timeout = '10s'
grace_period = '5s'
method = 'GET'
path = '/'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[statics]]
guest_path = '/app/build/client'
url_prefix = '/'
